services:
  - type: worker
    name: ical-to-notion-sync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python script.py
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: ICAL_URL
        sync: false
